### ISSUE TITLE
example/tsconfig.json is incorrect

### ISSUE THREAD

**Issue by leumasme** [Karibash/typescript-library-template#2]
`example/tsconfig.json` seems to be set up for `example` to also have its source code in a `src` folder - this is not the case, thus the tsconfig properties ` "include": ["src/**/*.ts"]` and `"rootDir": "src",` break.

**Comment by Karibash** [comment]
When I changed the following commit to use preconstruct for the build tool, I also fixed this bug.
https://github.com/Karibash/typescript-library-template/commit/3fcdcd766b92c14af8ceb197e107fc9eb2b044e1
